name: Build Electron

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

concurrency:
  group: build-electron-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-electron:
    if: github.event.inputs.mac-only != 'true'
    runs-on: ubuntu-latest

    outputs:
      build_type: ${{ steps.determine_build_type.outputs.build_type }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 25

      - name: Install dependencies
        run: |
          npm install -g typescript tsc-alias
          npm install

      - name: Compile TypeScript
        run: |
          npm run build

      - name: Build frontend
        run: |
          cd front
          npm install
          npm run build

      - name: Determine build type
        id: determine_build_type
        run: |
          if [ -z "${{ github.event.inputs.build-type }}" ]; then
            echo "build_type=full" >> $GITHUB_OUTPUT
            echo "BUILD_TYPE=full" >> $GITHUB_ENV
          else
            echo "build_type=${{ github.event.inputs.build-type }}" >> $GITHUB_OUTPUT
            echo "BUILD_TYPE=${{ github.event.inputs.build-type }}" >> $GITHUB_ENV
          fi

      - name: 🍷 Setup Wine & base Linux tools
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine32 wine64 libarchive-tools pacman fakeroot rpm

      - name: Full build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx electron-builder --publish always --win --linux

  build-mac:
    name: 🍏 Build macOS
    runs-on: macos-latest
    needs: build-electron

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install dependencies
        run: |
          npm install -g typescript tsc-alias
          npm install

      - name: Compile TypeScript
        run: |
          npm run build

      - name: Build frontend
        run: |
          cd front
          npm install
          npm run build

      - name: Build macOS app (no code signing)
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx electron-builder --mac zip
